# Generated by Django 3.1.5 on 2021-01-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0002_address_gallery_galleryimage_newspost_newspostimage_person_surveyresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='newspostimage',
            name='news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_post_image', to='wayzata76_web.newspost'),
        ),
    ]
