# Generated by Django 3.1.5 on 2021-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0003_contactinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='newspost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='link_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
