# Generated by Django 3.1.5 on 2021-01-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0003_auto_20210114_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='wayzata76_web.address'),
        ),
    ]
