# Generated by Django 3.1.5 on 2021-02-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0004_surveyresult_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='newspostimage',
            options={'ordering': ('-pk',)},
        ),
    ]
