# Generated by Django 3.1.5 on 2021-01-22 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wayzata76_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0006_auto_20210121_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('cover', models.ImageField(upload_to=wayzata76_web.models.yearbook_cover_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yearbooks', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yearbook', to='wayzata76_web.gallery')),
            ],
        ),
    ]
