# Generated by Django 3.1.5 on 2021-03-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0006_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='video_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
