# Generated by Django 3.1.5 on 2021-03-15 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import uuid
import wayzata76_web.models
import wayzata76_web.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0007_auto_20210305_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('body', djrichtextfield.models.RichTextField()),
                ('footnote', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomepagePostImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=wayzata76_web.storage_backends.PublicMediaStorage, upload_to=wayzata76_web.models.homepage_post_image_path)),
                ('homepage_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_post_image', to='wayzata76_web.homepagepost')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homepage_post_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'abstract': False,
            },
        ),
    ]
