# Generated by Django 3.1.5 on 2021-01-22 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0007_yearbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearbook',
            name='id',
        ),
        migrations.AddField(
            model_name='yearbook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
