# Generated by Django 3.1.5 on 2021-01-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0008_auto_20210122_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='section',
            field=models.TextField(choices=[('REUNIONS', 'Reunions'), ('STUDENT_LIFE', 'Student Life'), ('STOMPING_GROUNDS', 'The Stomping Grounds')], null=True),
        ),
        migrations.CreateModel(
            name='SubGallery',
            fields=[
                ('gallery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wayzata76_web.gallery')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_galleries', to='wayzata76_web.gallery')),
            ],
            bases=('wayzata76_web.gallery',),
        ),
    ]
