# Generated by Django 3.1.5 on 2021-03-16 03:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0008_homepagepost_homepagepostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepost',
            name='body',
            field=tinymce.models.HTMLField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=tinymce.models.HTMLField(max_length=5000),
        ),
    ]
