# Generated by Django 3.1.5 on 2021-01-24 01:29

from django.db import migrations, models
import wayzata76_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0009_auto_20210123_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='file',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(null=True, upload_to=wayzata76_web.models.gallery_for_image),
        ),
    ]
