# Generated by Django 3.1.5 on 2021-01-24 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0010_auto_20210123_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgallery',
            name='parent',
            field=models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.PROTECT, related_name='sub_galleries', to='wayzata76_web.gallery'),
        ),
    ]
