# Generated by Django 3.1.5 on 2021-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0010_homepagepostimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagepost',
            name='title',
            field=models.CharField(default='test_title', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='submitted_by',
            field=models.CharField(default='test_submitter', max_length=100),
            preserve_default=False,
        ),
    ]
