# Generated by Django 3.1.5 on 2021-03-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0011_auto_20210318_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
