# Generated by Django 3.1.5 on 2021-03-19 03:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0012_auto_20210319_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepost',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=tinymce.models.HTMLField(default='test-body', max_length=5000),
            preserve_default=False,
        ),
    ]
