# Generated by Django 3.1.5 on 2021-03-24 00:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0013_auto_20210319_0337'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
