# Generated by Django 3.1.5 on 2021-03-24 00:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0014_auto_20210324_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='body',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True),
        ),
    ]
