# Generated by Django 3.1.5 on 2021-03-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wayzata76_web', '0015_auto_20210324_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='link',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='link_text',
        ),
    ]
